done
JohnyRLk/jak-to-zrobic-w-ts pull request #1
Opened 2021-07-09 11:29 UTC by JohnyRLk

jak to zrobic w ts
Zrobione

1. Zrobilem wszystkie z  - home-actions.spec
2. Zrobilem wszystkie z  - home-items.spec
3.  Nie wiem o jaki element chodzi w tym tescie xit("powinna posiadac stopkę z linkami do ...", async function() }); - home-items.spec
4. Wiem, ze osposob jest zly, poniewaz element moze byc dalej na stronie ale w innym miejscu, ale nie mam pomyslu anrazie na inny sposob, po xpath znajduje w devtoolsach, ale nie znajduje juz go test.
it("powinna posiadac menu z pierwszym elementem 'OPONY WG ROZMIARU'", async function() {
    await browser.get(url);
    const getTextFromMenu = await $$('ul.nav li').get(0).getText();
    expect(getTextFromMenu).toEqual('OPONY WG ROZMIARU');
  }); - home-items.spec

2021-07-09 11:52 UTC, rafalszmit commented on spec/home-actions.spec.ts
> +    expect(browser.getCurrentUrl()).toContain("dostawcza");
The same expect as it was in previous test. This test will fail as there is no 'dostawcza' in the URL if you choose '4x4'. This means you did not run this test to check if it is working ;)

2021-07-09 11:52 UTC, rafalszmit commented on spec/home-items.spec.ts
> +    const getMenuItems = await element.all(by.css('ul.nav li')).map((el)=>{
you can also write it in a shorter way.
1. when you use css selector and not xpath you can use '$' or '$$' instead of element.all(by.css...
2. when using array methods like .map you don't have to type retrun, example from internet:

materials.map((material) => {
  return material.length;
}); // [8, 6, 7, 9]

materials.map(material => material.length); // [8, 6, 7, 9]

2021-07-09 12:04 UTC, MichalFidor commented on spec/home-actions.spec.ts
> +    expect(header).toEqual("Opony");
This one is passing? const header is just an element, not text

2021-07-13 10:30 UTC, rafalszmit commented on spec/external-functions.spec.ts
> +    let height = element(by.css("span.WyborOpon-Lewy-Item:nth-child(2) > span:nth-child(2) > span:nth-child(1) > span:nth-child(2)"));
you can make it shorter e.g:
`let height = $('[aria-controls="opona-profil_listbox"]');`
You don't have to change every selector now, but I guess it would a good training. Maybe try at least change the other dropdown selector to look more like the one above.

2021-07-14 06:44 UTC, MichalFidor requested changes

2021-07-14 06:44 UTC, MichalFidor commented on spec/home-actions.spec.ts
> +    let getTiresText = await element(by.css('//div/h1[text()="Lista opon"]'));
This is xpath, not css

2021-07-14 06:44 UTC, MichalFidor commented on spec/home-items.spec.ts
> +    let getAHref = await element.all(by.css(".navbar-nav   li  a")).map((el) => {return el.getAttribute("href");});
Remove white spaces. Did you used format on all files?

2021-07-16 05:43 UTC, merged